### ISSUE TITLE
CacheMethodMd5Sum hash checking fails when using coreutils' md5sum

### ISSUE THREAD

**Issue by jcreigh** [JacisNonsense/EmbeddedTools#13]
When coreutils is installed on the RoboRIO, the system starts using its `md5sum` instead of busybox's. This causes an error and leads to CacheMethodMd5Sum believing _all_ the hashes failed to match.

https://github.com/JacisNonsense/EmbeddedTools/blob/f38dda39649c3a045bb83137b32cf03e016b21ea/src/main/groovy/jaci/gradle/deploy/cache/CacheMethodMd5Sum.groovy#L31

The `md5sum -b -c _tmp.et.md5` command on the line above is the culprit. Busybox ignores the `-b` flag and does the checks properly, while coreutil's errors with:

`the --binary and --text options are meaningless when verifying checksums`

The `-b` flag does nothing, and there shouldn't be any issues removing it.

**Comment by JacisNonsense** [comment]
This should be fixed now. There's also some more debugging information included in the deploy process for if cache false-negatives keep occuring
