### ISSUE TITLE
Proper debug buildType

### ISSUE THREAD

**Issue by JacisNonsense** [JacisNonsense/EmbeddedTools#17]
Yet to experiment on if we can do buildTypes for debug without rebuilding all sources twice, but if so then we can link these to the dependencies for debug libs

**Comment by ThadHouse** [comment]
You wouldn't want to use the same builds for debug and release. Often, they're done with much different compiler args and optimization levels. Is this just the buildType stuff we added for the season? If so this can be closed.

**Comment by JacisNonsense** [comment]
Yup
