### ISSUE TITLE
Ability to change SSH port for deploy tasks

### ISSUE THREAD

**Issue by Endoman123** [JacisNonsense/EmbeddedTools#4]
Would there be a way to add a field for the SSH port to use for deploy tasks, for devices not listening for SSH on port 22?

**Comment by JacisNonsense** [comment]
Not currently, but I can add that in shortly

**Comment by JacisNonsense** [comment]
Added in 2018.01.20. Use `host:port` in the addresses like usual (e.g. `addresses << 'myhost:8080'`)
